feat: life events
monicahq/chandler pull request #412
Opened 2023-01-17 02:35 UTC by djaiss

The core of the app.😱

2023-02-08 23:07 UTC, asbiin requested changes
See my comments:

2023-02-08 23:07 UTC, asbiin commented on app/Domains/Contact/ManageLifeEvents/Web/Controllers/ContactModuleTimelineEventController.php
> +            'amount_lent' => $request->input('amount_lent') ? $request->input('amount_lent') * 100 : null,
All currency are not working like that, this needs more backend

2023-02-08 23:07 UTC, asbiin commented on app/Models/TimelineEvent.php
> +                    ' - '.
```suggestion
                    ' — '.
```

2023-02-08 23:07 UTC, asbiin commented on database/migrations/2023_02_01_021117_add_default_dashboard_tab_to_vaults.php
> +};
You can create a breaking change (like in the previous migration file), **OR** create a new migration file for 1 column, but not both. Please add this migration in the original `vaults` table creation migration.

2023-02-08 23:07 UTC, asbiin commented on resources/js/Shared/Modules/LifeEvent.vue
> +  if (confirm('Are you sure? This will delete the event permanently.')) {
Can you use the `ConfirmationModal` module instead?

2023-02-09 13:09 UTC, djaiss commented on app/Domains/Contact/ManageLifeEvents/Web/Controllers/ContactModuleTimelineEventController.php
> +            'amount_lent' => $request->input('amount_lent') ? $request->input('amount_lent') * 100 : null,
Oh shit it's a mistake. I forgot to delete this method.

2023-02-09 13:10 UTC, djaiss commented on database/migrations/2023_02_01_021117_add_default_dashboard_tab_to_vaults.php
> +};
You are right. Deleting.

2023-02-10 02:28 UTC, merged